---
apiVersion: v1
kind: ReplicationController
metadata:
  name: replica
spec: 
  replicas: 5
  selector: 
    name: demo
  template: 
    metadata:
      name: nginx
      labels: 
        name: demo
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
